# public/admin/config.yml
backend:
  # Usaremos el backend git-gateway para integración con Netlify/Vercel
  name: git-gateway
  branch: main # La rama de producción del proyecto
  squash_merges: true

# ----------------------------------------------------
# Configuración de Medios
# ----------------------------------------------------
media_folder: "public/assets/uploads" # Dónde se guardan las imágenes en tu repositorio
public_folder: "/assets/uploads"     # URL base para acceder a esas imágenes
display_url: https://elevawod.netlify.app # URL de tu sitio (ejemplo, ajustar en despliegue)

# ----------------------------------------------------
# Colecciones de Contenido (Modelos de Datos)
# ----------------------------------------------------
collections:
  - name: 'pages'
    label: 'Páginas del Sitio'
    files:
      - file: "src/content/pages/home.md"
        label: "Página Principal (Landing)"
        name: "home"
        # Estructura de campos para la Home Page
        fields:
          - {label: "Plantilla", name: "template", widget: "hidden", default: "home"}
          - {label: "Título SEO", name: "title", widget: "string", hint: "Título de la página para buscadores. Máx. 60 caracteres."}
          - {label: "Meta Descripción", name: "description", widget: "text", hint: "Descripción corta para SEO. Máx. 155 caracteres."}
          - {label: "URL Canónica", name: "canonical_url", widget: "string", required: false, hint: "La URL preferida para esta página, ej: https://elevawod.cl/"}
          - {label: "Meta Robots", name: "robots", widget: "string", required: false, hint: "Instrucciones para robots, ej: index, follow / noindex, nofollow"}
          - label: "Open Graph / Redes Sociales"
            name: "og"
            widget: "object"
            required: false
            fields:
              - {label: "Título OG", name: "title", widget: "string", required: false, hint: "Título para redes sociales"}
              - {label: "Descripción OG", name: "description", widget: "text", required: false}
              - {label: "Imagen OG", name: "image", widget: "image", required: false, hint: "Imagen para compartir en redes (1200x630 px recomendado)"}

          # Hero
          - label: "Sección Hero"
            name: "hero"
            widget: "object"
            required: false
            fields:
              - {label: "Imagen de Fondo (Hero)", name: "background_image", widget: "image", required: false, hint: "Imagen principal del hero. Recomendado 2000x1200 px."}
              - {label: "Título (Hero)", name: "title", widget: "string", required: false, hint: "Texto principal grande del hero."}
              - {label: "Subtítulo (Hero)", name: "subtitle", widget: "string", required: false, hint: "Texto secundario del hero."}
              - {label: "CTA Principal (texto)", name: "cta_text", widget: "string", required: false, hint: "Texto del botón principal, ej: 'Contactar'."}
              - {label: "CTA URL (link)", name: "cta_url", widget: "string", required: false, hint: "URL o anchor para el botón CTA, ej: /contacto o https://wa.me/569..."}

          # Nosotros
          - label: "Sección Nosotros"
            name: "nosotros"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Nosotros)", name: "title", widget: "string", required: false, hint: "Título de la sección 'Nosotros'."}
              - {label: "Descripción (Nosotros)", name: "content", widget: "text", required: false, hint: "Breve descripción o historia de la empresa."}
              - {label: "Imagen (Nosotros)", name: "image", widget: "image", required: false, hint: "Imagen representativa de la empresa o equipo."}

          # Servicios
          - label: "Nuestros Servicios"
            name: "servicios"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Servicios)", name: "title", widget: "string", required: false, hint: "Título general de la sección de servicios."}
              - {label: "Subtítulo (Servicios)", name: "subtitle", widget: "string", required: false, hint: "Subtítulo opcional para la sección."}
              - label: "Lista de Servicios"
                name: "lista"
                widget: "list"
                required: false
                fields:
                  - {label: "Título del Servicio", name: "title", widget: "string", required: true, hint: "Nombre del servicio, ej: 'Desarrollo Web'."}
                  - {label: "Subtítulo (opcional)", name: "subtitle", widget: "string", required: false}
                  - {label: "Descripción", name: "description", widget: "text", required: false, hint: "Breve descripción del servicio."}
                  - {label: "Imagen (opcional)", name: "image", widget: "image", required: false, hint: "Icono o imagen representativa del servicio."}

          # Testimonios / Clientes
          - label: "Lo que dicen nuestros clientes"
            name: "clientes"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Testimonios)", name: "title", widget: "string", required: false}
              - label: "Lista de Testimonios"
                name: "lista"
                widget: "list"
                required: false
                fields:
                  - {label: "Texto del Testimonio", name: "quote", widget: "text", required: true, hint: "Cita del cliente."}
                  - {label: "Autor", name: "author", widget: "string", required: false, hint: "Nombre del cliente o empresa."}
                  - {label: "Google Review Embed (HTML)", name: "google_review_embed", widget: "text", required: false, hint: "Pega el código de incrustación de una reseña específica de Google si quieres mostrarla incrustada."}

  - name: 'proyectos'
    label: 'Portafolio / Proyectos'
    folder: 'src/content/proyectos'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Slug (URL Amigable)", name: "slug", widget: "string", hint: "Parte de la URL, ej: mi-primer-proyecto. Usar solo minúsculas, números y guiones."}
      - label: "Cliente (Nombre o Empresa)"
        name: "client_name"
        widget: "string"
        required: true
      - label: "Título del Proyecto"
        name: "title"
        widget: "string"
      - label: "Servicios Realizados"
        name: "services_list"
        widget: "list"
        required: false
        fields:
          - label: "Servicio"
            name: "item"
            widget: "string"
      - label: "Fecha"
        name: "date"
        widget: "datetime"
        required: false
      - label: "Resumen (Descripción Corta)"
        name: "summary"
        widget: "text"
        required: false
      - label: "Contenido Detallado"
        name: "body"
        widget: "markdown"
        required: false
      - label: "Galería de Fotos"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - label: "Imagen"
            name: "image_path"
            widget: "image"

  - name: 'ajustes'
    label: 'Ajustes del Sitio'
    files:
      - file: "src/content/ajustes/home.yml"
        label: "Ajustes de la Página de Inicio"
        name: "home_settings"
        fields:
          - label: "Proyectos Destacados en la Portada"
            name: "proyectos_destacados"
            hint: "Selecciona hasta 3 proyectos para mostrar en la página de inicio."
            widget: "list"
            required: false
            fields:
              - {label: "Slug del Proyecto", name: "slug", widget: "string", hint: "usa el slug del proyecto"}

  - name: 'informacion-de-contacto'
    label: 'Información de Contacto'
    files:
      - file: "src/content/informacion-de-contacto/general.yml"
        label: "Información General de Contacto"
        name: "general"
        fields:
          - {label: "Número de WhatsApp", name: "whatsapp", widget: "string", hint: "Número para WhatsApp sin +, ej: 56912345678", required: false}
          - {label: "Teléfono fijo / alternativo", name: "phone", widget: "string", required: false, hint: "Teléfono adicional (opcional)."}
          - {label: "Correo Electrónico Principal", name: "email", widget: "string", hint: "Correo electrónico principal de contacto.", required: false}
          # Correos secundarios eliminados: ahora solo hay un correo principal en la configuración.
          - {label: "Dirección", name: "address", widget: "string", hint: "Dirección física de la empresa.", required: false}
          - {label: "Título sección Contacto", name: "contact_heading", widget: "string", required: false, hint: "Ej: ¿Listo para empezar?"}
          - {label: "Subtítulo sección Contacto", name: "contact_subheading", widget: "text", required: false, hint: "Ej: Conversemos por WhatsApp para una respuesta más rápida o envíame un correo."}
          - label: "Mensaje por defecto para WhatsApp"
            name: "whatsapp_message"
            widget: "text"
            required: false
            hint: "Mensaje que se enviará al abrir el chat de WhatsApp. Ej: Hola, vengo de Elevawod.cl y quiero cotizar un proyecto"
          - {label: "Mostrar sección de contacto pública", name: "show_contact_section", widget: "boolean", required: false, default: true, hint: "Si está desactivado, la sección de contacto no se mostrará en el frontend."}