# public/admin/config.yml
backend:
  name: git-gateway
  branch: main
  squash_merges: true

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
display_url: https://elevawod.netlify.app

# ----------------------------------------------------
# Colecciones de Contenido (Ahora organizadas por roles)
# ----------------------------------------------------
collections:
  # 1. Tareas de SEO / Técnicas
  - name: 'seo_global'
    label: 'SEO / Metadatos (Home)'
    files:
      - file: "src/content/pages/home.md"
        label: "Metadatos de la Página Principal"
        name: "home_seo"
        fields:
          # Aquí solo ponemos los campos de SEO que ya definiste
          - {label: "Plantilla", name: "template", widget: "hidden", default: "home"}
          - {label: "Título SEO", name: "title", widget: "string", hint: "Título de la página."}
          - {label: "Meta Descripción", name: "description", widget: "text", hint: "Descripción corta para SEO. Máx. 155 caracteres."}
          - {label: "URL Canónica", name: "canonical_url", widget: "string", required: false, hint: "La URL preferida para esta página, ej: https://elevawod.cl/"}
          - {label: "Meta Robots", name: "robots", widget: "string", required: false, hint: "Instrucciones para robots, ej: index, follow / noindex, nofollow"}
          - label: "Open Graph / Redes Sociales"
            name: "og"
            widget: "object"
            required: false
            fields:
              - {label: "Título OG", name: "title", widget: "string", required: false, hint: "Título para redes sociales"}
              - {label: "Descripción OG", name: "description", widget: "text", required: false}
              - {label: "Imagen OG", name: "image", widget: "image", required: false, hint: "Imagen para compartir en redes (1200x630 px recomendado)"}

  # 2. Contenido de la Página Principal (dividido en secciones)
  # HERO
  - name: 'home_hero'
    label: 'Home: Sección Hero'
    files:
      - file: "src/content/pages/home.md"
        label: "Contenido de la Sección Hero"
        name: "hero_content"
        fields:
          - label: "Sección Hero"
            name: "hero"
            widget: "object"
            required: false
            fields:
              - {label: "Imagen de Fondo (Hero)", name: "background_image", widget: "image", required: false, hint: "Imagen principal del hero. Recomendado 2000x1200 px."}
              - {label: "Título (Hero)", name: "title", widget: "text", required: false, hint: "Texto principal/Título del hero."}
              - {label: "Subtítulo (Hero)", name: "subtitle", widget: "markdown", required: false, hint: "Subtítulo del hero."}
              - {label: "CTA Principal (texto)", name: "cta_text", widget: "string", required: false, hint: "Texto del botón principal, ej: 'Contactar'."}
              - {label: "CTA URL (link)", name: "cta_url", widget: "string", required: false, hint: "URL para el botón CTA; Sección interna ej: /contacto, o Enlace externo ej: https://wa.me/584... o https://calendly.com/..."}

  # NOSOTROS
  - name: 'home_nosotros'
    label: 'Home: Sección Nosotros'
    files:
      - file: "src/content/pages/home.md"
        label: "Contenido de la Sección Nosotros"
        name: "nosotros_content"
        fields:
          - label: "Sección Nosotros"
            name: "nosotros"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Nosotros)", name: "title", widget: "text", required: false, hint: "Título de la sección 'Nosotros'."}
              - {label: "Descripción (Nosotros)", name: "content", widget: "markdown", required: false, hint: "Breve descripción."}
              - {label: "Imagen (Nosotros)", name: "image", widget: "image", required: false, hint: "Imagen representativa de la empresa o equipo."}

  # SERVICIOS "SECCIÓN"
  - name: 'home_servicios'
    label: 'Home: Sección Servicios'
    files:
      - file: "src/content/pages/home.md"
        label: "Contenido de la Sección Servicios"
        name: "servicios_content"
        fields:
          - label: "Nuestros Servicios"
            name: "servicios"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Servicios)", name: "title", widget: "text", required: false, hint: "Título general de la sección de servicios."}
              - {label: "Subtítulo (Servicios)", name: "subtitle", widget: "text", required: false, hint: "Subtítulo opcional para la sección."}

  # SERVICIOS "COLECCIÓN ""
  - name: 'servicios'
    label: 'Coleeción de Servicios de la Empresa'
    folder: 'src/content/servicios'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Nombre del Servicio", name: "title", widget: "text", required: true}
      - {label: "Subtítulo (opcional)", name: "subtitle", widget: "text", required: false}
      - {label: "Descripción", name: "description", widget: "markdown", required: false}
      - {label: "Imagen (opcional)", name: "image", widget: "image", required: false}

  # TESTIMONIOS
  - name: 'home_clientes'
    label: 'Home: Sección Testimonios'
    files:
      - file: "src/content/pages/home.md"
        label: "Contenido de la Sección Testimonios"
        name: "clientes_content"
        fields:
          - label: "Lo que dicen nuestros clientes"
            name: "clientes"
            widget: "object"
            required: false
            fields:
              - {label: "Título (Testimonios)", name: "title", widget: "text", required: false}
              - label: "Lista de Testimonios"
                name: "lista"
                widget: "list"
                required: false
                fields:
                  - {label: "Texto del Testimonio", name: "quote", widget: "markdown", required: true, hint: "Cita del cliente."}
                  - {label: "Autor", name: "author", widget: "text", required: false, hint: "Nombre del cliente o empresa."}
                  - {label: "Google Review Embed (HTML)", name: "google_review_embed", widget: "text", required: false, hint: "Pega el código de incrustación de una reseña específica de Google si quieres mostrarla incrustada."}

  # 3. Contenido del Portafolio
  # Proyectos
  - name: 'proyectos'
    label: 'Proyectos / Portafolio'
    folder: 'src/content/proyectos'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Slug (URL Amigable)", name: "slug", widget: "string", hint: "Parte final de la URL, ej: mi-primer-proyecto. Usar solo minúsculas, números y guiones. Resultado: mi-sitio.com/proyectos/mi-primer-proyecto", required: true}
      - {label: "Cliente (Nombre o Empresa)", name: "client_name", widget: "text", required: true}
      - {label: "Título del Proyecto", name: "title", widget: "text"}
      - {label: "Servicios Realizados", name: "services_list", widget: "relation", collection: "servicios", multiple: true, search_fields: ["title"], value_field: "title", display_fields: ["title"], required: false}
      - {label: "Fecha", name: "date", widget: "datetime", time_format: false, date_format: "YYYY-MM-DD", required: false}
      - {label: "Resumen (Descripción Corta)", name: "summary", widget: "markdown", required: false}
      - {label: "Contenido Detallado", name: "project_details", widget: "markdown", required: false}
      - {label: "Galería de Fotos", name: "gallery", widget: "list", required: false, fields: [{label: "Imagen", name: "image_path", widget: "image"}]}

  # 4. Proyectos Destacados
  - name: 'ajustes'
    label: 'Proyectos Destacados (Home)'
    files:
      - file: "src/content/ajustes/home.yml"
        label: "Proyectos Destacados (Home)" 
        name: "home_settings"
        fields:
          - label: "Proyectos Destacados en la Portada"
            name: "proyectos_destacados"
            hint: "Selecciona los proyectos que aparecerán en la página de inicio."
            widget: "relation"
            collection: "proyectos"
            multiple: true
            max: 3
            search_fields: ["title", "client_name"]
            value_field: "slug"
            display_fields: ["title"]

  # 5. Información de Contacto    
  - name: 'informacion-de-contacto'
    label: 'Información de Contacto'
    files:
      - file: "src/content/informacion-de-contacto/general.yml"
        label: "Información General de Contacto"
        name: "general"
        fields:
          - {label: "Número de WhatsApp", name: "whatsapp", widget: "string", hint: "Número para WhatsApp sin +, ej: 56912345678", required: false}
          - {label: "Teléfono fijo / alternativo", name: "phone", widget: "string", required: false, hint: "Teléfono adicional (opcional)."}
          - {label: "Correo Electrónico Principal", name: "email", widget: "string", hint: "Correo electrónico principal de contacto.", required: false}
          # Correos secundarios eliminados: ahora solo hay un correo principal en la configuración.
          - {label: "Dirección", name: "address", widget: "markdown", buttons: ["bold", "italic", "link"], hint: "Dirección física de la empresa.", required: false}
          - {label: "Título sección Contacto", name: "contact_heading", widget: "text", required: false, hint: "Ej: ¿Listo para empezar?"}
          - {label: "Subtítulo sección Contacto", name: "contact_subheading", widget: "text", required: false, hint: "Ej: Conversemos por WhatsApp para una respuesta más rápida o envíame un correo."}
          - label: "Mensaje por defecto para WhatsApp"
            name: "whatsapp_message"
            widget: "text"
            required: false
            hint: "Mensaje que se enviará al abrir el chat de WhatsApp. Ej: Hola, vengo de Elevawod.cl y quiero cotizar un proyecto"
          - {label: "Mostrar sección de contacto pública", name: "show_contact_section", widget: "boolean", required: false, default: true, hint: "Si está desactivado, la sección de contacto no se mostrará en el frontend."}